Given a matrix: produce a matrix in row echelon form (REF). <br>
By using elementary row operations: interchange, scaling and replacement.<br>
definition: A matrix is in REF if it satisfies the following conditions:<br>
1) If it has zero rows, it must be at the bottom of the matrix.<br>
2) Leading entry in each row non-zero row is 1. <br>
3) Each leadin is the to the right of all leading 1's above it.<br>


In [10]:
matrix = [
          [0,2,1,1,3],
          [0,-1,2,2,1],
          [0,1,-1,-3,-6]
         ]
matrix2 = [[ 0 , 1 ,-1, -3, -6],
 [ 0,  0 , 1 ,-1 ,-5],
 [ 0,  0  ,3 , 7 ,15]]
matrix3 = [[2,1,1,3],
           [-1,2,2,1],
           [1,-1,-3,-6]]
matrix4 = [[2,4,2],[8,8,1]]



In [34]:
import numpy as np
import copy
def print_useful(g):
    'after one iteration, before update:' 
    print 'g.row',g.row,'g.col',g.col
    print 'g.leading',g.leading
    print g.m
    print 'done:',g.done()
    print '-------------------------------------'

class Gaussian:
    def __init__(self, matrix):
        self.m = np.array(self.float_it(matrix))
        self.col = 0
        self.row = 0
        self.leading = None
    
    def float_it(self,matrix):
        for i,row in enumerate(matrix):
            for j,col in enumerate(row):
                matrix[i][j] = float(matrix[i][j])
        return matrix
    
         
    def all_zeros(self):
        return not np.any(self.m)
    
    def interchange(self,row_i,row_j):
        tmp = self.m[row_j].copy()
        self.m[row_j] = self.m[row_i]
        self.m[row_i] = tmp
    
    def scale(self,K,row_i):
        scaled_row = K*self.m[row_i]
        self.m[row_i] = scaled_row
        
    def scale_for_rep(self,K,row_i):
        matrix = self.m.copy()
        return -K*matrix[row_i]
    
    def replace(self,K,row_i,row_j):
        scaled_row = self.scale_for_rep(K,row_i)
        replace_row = self.m[row_j]
        self.m[row_j] = [i + j for i,j in zip(scaled_row, replace_row)]
        
                      
    def first_none_zero_elt(self,col):
        for r_idx,elt in enumerate(col):
            if (elt != 0 and r_idx >= self.row ):
                return r_idx,elt
        return None,None
    
    def update(self,r,c,l):
        self.row = r
        self.col = c
        self.leading = l
        
    def reset_leading(self):
        self.leading = None
        self.row +=1
        self.col +=1
        
        
    def find_one(self):
        for r_idx,elt in enumerate (self.m.T[self.col]):
            if (elt == 1):
                self.interchange(r_idx,self.row)
                self.leading = 1
                break
        if (self.leading != 1):
            K = 1/float(self.leading)
            self.scale(K,self.row)
    
    
    def do_replacements(self):
        for r_idx,elt in enumerate(self.m.T[self.col]):
            if (elt != 0 and r_idx > self.row):
                K = elt
                self.replace(K,self.row,r_idx)
        
        
    def find_leading(self):
        for c_idx,col in enumerate(self.m.T):
            not_all_zero = np.any(col)
            if (not_all_zero and c_idx >= self.col):
                r_idx,elt = self.first_none_zero_elt(col)
                self.update(r_idx,c_idx,elt)
                break
        
        if (self.leading != 1):
            self.find_one()

    #are we done yet? 
    def done(self):
        return self.row >= len(self.m)
    
    def produce_REF(self):
        while(not self.done()):
            self.find_leading()
            self.do_replacements()
            self.reset_leading()
        return self.m
    


In [35]:
gauss = Gaussian(matrix)
REF = gauss.produce_REF()
print REF


g.row 0 g.col 1
g.leading 1
[[  0.   1.  -1.  -3.  -6.]
 [  0.   0.   1.  -1.  -5.]
 [  0.   0.   3.   7.  15.]]
done: False
-------------------------------------
g.row 1 g.col 2
g.leading 1.0
[[  0.   1.  -1.  -3.  -6.]
 [  0.   0.   1.  -1.  -5.]
 [  0.   0.   0.  10.  30.]]
done: False
-------------------------------------
g.row 2 g.col 3
g.leading 10.0
[[ 0.  1. -1. -3. -6.]
 [ 0.  0.  1. -1. -5.]
 [ 0.  0.  0.  1.  3.]]
done: False
-------------------------------------
[[ 0.  1. -1. -3. -6.]
 [ 0.  0.  1. -1. -5.]
 [ 0.  0.  0.  1.  3.]]


In [ ]:
def test(matrix):
    g = Gaussian(matrix)
    print_useful(g)
    g.find_leading()
    g.do_replacements()
    print_useful(g)
    g.find_leading()
    g.do_replacements()
    print_useful(g)
    g.find_leading()
    g.do_replacements()
    print_useful(g)
    
    
test(matrix)

In [ ]:
def test2(matrix):
    g = Gaussian(matrix)
    g.find_leading()
    print_useful(g)
    g.do_replacements()
    print_useful(g)
    g.find_leading()
    print_useful(g)
    print g.row - (len(g.m) -1)
test2(matrix4)