Given a matrix: produce a matrix in row echelon form (REF). <br>
By using elementary row operations: interchange, scaling and replacement.<br>
definition: A matrix is in REF if it satisfies the following conditions:<br>
1) If it has zero rows, it must be at the bottom of the matrix.<br>
2) Leading entry in each row non-zero row is 1. <br>
3) Each leadin is the to the right of all leading 1's above it.<br>


In [16]:
matrix = [
          [0,2,1,1,3],
          [0,-1,2,2,1],
          [0,1,-1,-3,-6]
         ]
matrix2 = [[ 0 , 1 ,-1, -3, -6],
 [ 0,  0 , 1 ,-1 ,-5],
 [ 0,  0  ,3 , 7 ,15]]

In [20]:
import numpy as np
import copy


class Gaussian:
    def __init__(self, matrix,rows_completed):
        self.m = np.array(matrix)
        self.rc = rows_completed
        self.col = 0
        self.row = 0
        self.leading = None
        self.inter_row = None
        self.leading_is_one = False
    
        
        
        
        
        
    def all_zeros(self):
        return not np.any(self.m)
    
    def interchange(self,row_i,row_j):
        print self.row,self.col
        tmp = self.m[row_j].copy()
        self.m[row_j] = self.m[row_i]
        self.m[row_i] = tmp
    
    def scale(self,K,row_i):
        self.m[row_i] = K*self.m[row_i]
    def scale_for_rep(self,K,row_i):
        matrix = self.m.copy()
        return -K*matrix[row_i]
    
    
        
        
    def replace(self,K,row_i,row_j):
        scaled_row = self.scale_for_rep(K,row_i)
        #scaled_row = self.m[row_i]
        replace_row = self.m[row_j]
        self.m[row_j] = [i + j for i,j in zip(scaled_row, replace_row)]
        
                      
    def check_rows_below_leading(self):
        for row_i in range(self.row,len(matrix)):
            for col_j in range(row_i):
                if (self.m[col_j][row_i] == 1):
                    self.leading_is_one= True
                    self.inter_row = row_i
              
    #finds first none zero column, from the 0th to nth row
    def none_zero_col(self):
        found_leading = False
        for row_i in range(len(self.m)):
            for col_j in range(self.col,(row_i)):
                if (self.m[col_j][row_i] != 0):
                    self.row = col_j
                    self.col = row_i
                    self.leading = float(self.m[col_j][row_i])
                    found_leading = True
                    break
            if (found_leading):
                break

        if (self.m[self.row][self.col] == 1):
            self.leading_is_one = True
    
        
        
    #are we done yet? 
    def done(self):
        return self.rc ==  len(self.m) -1
        

In [34]:
def print_useful(g):
    'after one iteration, before update:' 
    print 'g.row',g.row,'g.col',g.col,'g.rc'
    print 'g.rc',g.rc
    print 'g.inter',g.inter_row
    print 'g.leadin_is_one',g.leading_is_one
    print 'g.leading',g.leading
    print g.m
    print '-------------------------------------'

def interchange_or_scale(g):
    if (not g.leading_is_one):
        g.check_rows_below_leading()   
    if (g.inter_row != None):
        g.interchange(g.inter_row,g.row)
    else:
        K = 1./g.leading
        g.scale(K,g.row)
    
def do_replacements(g):
    for rep_row in range(g.row+1,len(g.m)):
        int_below = g.m[rep_row][g.col]
        if (int_below == 0):
            continue
        g.replace(int_below,g.row,rep_row)
def update_vars(g):
    g.leading = None
    g.inter_row = None
    g.leading_is_one = False
    g.rc = g.rc + 1
    
def produce_REF(matrix):
    g = Gaussian(matrix,0)
    if (g.all_zeros()):
        return g.m
    
    while(not g.done()):
        g.none_zero_col()
        interchange_or_scale(g)
        do_replacements(g)
        update_vars(g)
    K = 0
    for col in g.m[-1]:
        if col != 0:
            K = col
            break
    g.m[-1] = g.m[-1]*1./K

    return g.m
            
REF = produce_REF(matrix)

    

0 1


In [22]:
def test():
    print "T1 ---- g ---"
    g = Gaussian(matrix,0)

    print "all zero:"
    print g.all_zeros()
    print "original matrix"
    print g.m
    print "row 0 <--> row 2"
    g.interchange(0,2)
    print g.m
    print "row 1 --> 2*row 1"
    g.scale(2,1)
    print g.m
    print "row 0 + row 2"
    g.replace(1,0,2)
    print g.m
    print "firt none zero pos"
    g.none_zero_col()
    print "r:",g.row,"c:",g.col
    print "leading is one:",g.leading_is_one
    print "1 below non zero: ", g.check_rows_below_leading()
     
test()
    

T1 ---- g ---
all zero:
False
original matrix
[[ 0  2  1  1  3]
 [ 0 -1  2  2  1]
 [ 0  1 -1 -3 -6]]
row 0 <--> row 2
0 0
[[ 0  1 -1 -3 -6]
 [ 0 -1  2  2  1]
 [ 0  2  1  1  3]]
row 1 --> 2*row 1
[[ 0  1 -1 -3 -6]
 [ 0 -2  4  4  2]
 [ 0  2  1  1  3]]
row 0 + row 2
[[ 0  1 -1 -3 -6]
 [ 0 -2  4  4  2]
 [ 0  1  2  4  9]]
firt none zero pos
r: 0 c: 1
leading is one: True
1 below non zero:  None


In [23]:
def test2():
    print "T1 ---- a ---"
    a = Gaussian(matrix,0)
    print "firt none zero pos"
    a.none_zero_col()
    print "r:",a.row,"c:",a.col
    print "leading is one:",a.leading_is_one
test2()



T1 ---- a ---
firt none zero pos
r: 0 c: 1
leading is one: False


In [24]:


def test3(matrix):
    matrix1,zero_rows = remove_zero_rows(matrix)
    g = Gaussian(matrix1,0)
    g.none_zero_col()
    interchange_or_scale(g)
    do_replacements(g)
    print_useful(g)
    update_vars(g)
    print_useful(g)
    g.none_zero_col()
    
    print_useful(g)
    interchange_or_scale(g)
    print_useful(g)
    do_replacements(g)
    print_useful(g)
    update_vars(g)
    
    g.none_zero_col()
    print_useful(g)
    
    


    
    
    
    
    
    
    
    
    
test3(matrix)

0 1
g.row 0 g.col 1 g.rc
g.rc 0
g.inter 2
g.leadin_is_one True
g.leading 2.0
[[ 0  1 -1 -3 -6]
 [ 0  0  1 -1 -5]
 [ 0  0  3  7 15]]
-------------------------------------
g.row 0 g.col 1 g.rc
g.rc 1
g.inter None
g.leadin_is_one False
g.leading None
[[ 0  1 -1 -3 -6]
 [ 0  0  1 -1 -5]
 [ 0  0  3  7 15]]
-------------------------------------
g.row 1 g.col 2 g.rc
g.rc 1
g.inter None
g.leadin_is_one True
g.leading 1.0
[[ 0  1 -1 -3 -6]
 [ 0  0  1 -1 -5]
 [ 0  0  3  7 15]]
-------------------------------------
g.row 1 g.col 2 g.rc
g.rc 1
g.inter None
g.leadin_is_one True
g.leading 1.0
[[ 0  1 -1 -3 -6]
 [ 0  0  1 -1 -5]
 [ 0  0  3  7 15]]
-------------------------------------
g.row 1 g.col 2 g.rc
g.rc 1
g.inter None
g.leadin_is_one True
g.leading 1.0
[[ 0  1 -1 -3 -6]
 [ 0  0  1 -1 -5]
 [ 0  0  0 10 30]]
-------------------------------------
g.row 1 g.col 2 g.rc
g.rc 2
g.inter None
g.leadin_is_one True
g.leading None
[[ 0  1 -1 -3 -6]
 [ 0  0  1 -1 -5]
 [ 0  0  0 10 30]]
--------------------